---
- hosts: laptop
  gather_facts: no
  vars:
    - enable_validation: true
    - release: 5.6
    - pkgs:
      - vim--no_x11
      - bash
      - git
      - jq
      - dmenu
      - dzen2
      - elinks
      - lynx
      - links
      - firefox
      - fswebcam
      - go
      - irssi--
      - irssi-xmpp
      - pftop
      - transmission
      - wget
      - curl
      - xmonad
    - daemons:
        unbound: -c /var/unbound/etc/unbound.conf
        ntpd:
        apmd: -A
        sensorsd:
        sndiod:
  tasks:
  - name: get arch
    command: uname -m
    register: arch
  - name: ensure site-wide pkg.conf contains installpath
    lineinfile:
      dest=/etc/pkg.conf
      backup=yes
      line="installpath = http://ftp.eu.openbsd.org/pub/OpenBSD/{{release}}/packages/{{arch.stdout}}/"
      regexp='^'
      state=present
      insertafter=EOF
      create=True 
  - name: install packages
    openbsd_pkg: name={{item}} state=present
    with_items: pkgs
  - name: configure rc.conf.local
    template: backup=yes dest=/etc/rc.conf.local owner=root mode=0644 src=templates/rc.conf.local.j2
  - name: copy misc /etc files 
    copy: src=files/{{item}} dest=/etc/{{item}} backup=yes owner=root mode=0644
    with_items: [dhclient.conf, resolv.conf.tail]
  - name: create unbound log dir
    file: path=/var/unbound/log owner=root group=_unbound mode=0775 state=directory
  - name: create unboound log file
    file: path=/var/unbound/log/unbound.log owner=_unbound group=wheel mode=0644 state=file
  - name: template unbound.conf
    template: backup=yes dest=/var/unbound/etc/unbound.conf owner=_unbound group=wheel mode=0644 src=templates/unbound.conf.j2
  - name: create crypto material for unbound-control
    command: unbound-control-setup -d /var/unbound/etc/
    args:
      creates: /var/unbound/etc/unbound_server.key
